/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hungr API
 * Private food sharing API for the Hungr application.
 * OpenAPI spec version: 1.0.0
 */
import type { FoodResponseDto } from './foodResponseDto';

export interface FoodDataDto {
  food: FoodResponseDto;
}
