/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hungr API
 * Private food sharing API for the Hungr application.
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type GetHealth200Error = {[key: string]: {
  status: string;
  [key: string]: unknown;
 }} | null;
