/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hungr API
 * Private food sharing API for the Hungr application.
 * OpenAPI spec version: 1.0.0
 */
import type { GetHealth200Details } from './getHealth200Details';
import type { GetHealth200Error } from './getHealth200Error';
import type { GetHealth200Info } from './getHealth200Info';

export type GetHealth200 = {
  status?: string;
  /** @nullable */
  info?: GetHealth200Info;
  /** @nullable */
  error?: GetHealth200Error;
  details?: GetHealth200Details;
};
