/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hungr API
 * Private food sharing API for the Hungr application.
 * OpenAPI spec version: 1.0.0
 */
import type { GetHealth503Details } from './getHealth503Details';
import type { GetHealth503Error } from './getHealth503Error';
import type { GetHealth503Info } from './getHealth503Info';

export type GetHealth503 = {
  status?: string;
  /** @nullable */
  info?: GetHealth503Info;
  /** @nullable */
  error?: GetHealth503Error;
  details?: GetHealth503Details;
};
