/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Hungr API
 * API for the Hungr food sharing app
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  PostApiFoodsBody,
  PostApiLoginBody,
  PostApiUsersBody,
  PutApiFoodsFoodIdBody,
  PutApiUsersUserIdBody
} from './model'



  export const getHungrAPI = () => {
/**
 * @summary Log in and receive a JWT
 */
const postApiLogin = <TData = AxiosResponse<void>>(
    postApiLoginBody: PostApiLoginBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/login`,
      postApiLoginBody,options
    );
  }

/**
 * @summary List users
 */
const getApiUsers = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/users`,options
    );
  }

/**
 * @summary Register a user
 */
const postApiUsers = <TData = AxiosResponse<void>>(
    postApiUsersBody: PostApiUsersBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/users`,
      postApiUsersBody,options
    );
  }

/**
 * @summary Get a user by id
 */
const getApiUsersUserId = <TData = AxiosResponse<void>>(
    userId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/users/${userId}`,options
    );
  }

/**
 * @summary Update a user
 */
const putApiUsersUserId = <TData = AxiosResponse<void>>(
    userId: string,
    putApiUsersUserIdBody: PutApiUsersUserIdBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/users/${userId}`,
      putApiUsersUserIdBody,options
    );
  }

/**
 * @summary Delete a user
 */
const deleteApiUsersUserId = <TData = AxiosResponse<void>>(
    userId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/users/${userId}`,options
    );
  }

/**
 * @summary List foods
 */
const getApiFoods = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/foods`,options
    );
  }

/**
 * @summary Create a food
 */
const postApiFoods = <TData = AxiosResponse<void>>(
    postApiFoodsBody: PostApiFoodsBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/foods`,
      postApiFoodsBody,options
    );
  }

/**
 * @summary Get a food by id
 */
const getApiFoodsFoodId = <TData = AxiosResponse<void>>(
    foodId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/foods/${foodId}`,options
    );
  }

/**
 * @summary Update a food
 */
const putApiFoodsFoodId = <TData = AxiosResponse<void>>(
    foodId: string,
    putApiFoodsFoodIdBody: PutApiFoodsFoodIdBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/foods/${foodId}`,
      putApiFoodsFoodIdBody,options
    );
  }

/**
 * @summary Delete a food
 */
const deleteApiFoodsFoodId = <TData = AxiosResponse<void>>(
    foodId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/foods/${foodId}`,options
    );
  }

/**
 * @summary API root status
 */
const getApi = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api`,options
    );
  }

/**
 * @summary Test auth GET endpoint
 */
const getApiAuth = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/auth`,options
    );
  }

/**
 * @summary Test auth POST endpoint
 */
const postApiAuth = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/auth`,undefined,options
    );
  }

/**
 * @summary Health check
 */
const getHealthz = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/healthz`,options
    );
  }

return {postApiLogin,getApiUsers,postApiUsers,getApiUsersUserId,putApiUsersUserId,deleteApiUsersUserId,getApiFoods,postApiFoods,getApiFoodsFoodId,putApiFoodsFoodId,deleteApiFoodsFoodId,getApi,getApiAuth,postApiAuth,getHealthz}};
export type PostApiLoginResult = AxiosResponse<void>
export type GetApiUsersResult = AxiosResponse<void>
export type PostApiUsersResult = AxiosResponse<void>
export type GetApiUsersUserIdResult = AxiosResponse<void>
export type PutApiUsersUserIdResult = AxiosResponse<void>
export type DeleteApiUsersUserIdResult = AxiosResponse<void>
export type GetApiFoodsResult = AxiosResponse<void>
export type PostApiFoodsResult = AxiosResponse<void>
export type GetApiFoodsFoodIdResult = AxiosResponse<void>
export type PutApiFoodsFoodIdResult = AxiosResponse<void>
export type DeleteApiFoodsFoodIdResult = AxiosResponse<void>
export type GetApiResult = AxiosResponse<void>
export type GetApiAuthResult = AxiosResponse<void>
export type PostApiAuthResult = AxiosResponse<void>
export type GetHealthzResult = AxiosResponse<void>
