/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Hungr API
 * API for the Hungr food sharing app
 * OpenAPI spec version: 1.0.0
 */

export type PutApiUsersUserIdBody = {
  email?: string;
  password?: string;
};
