/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hungr API
 * Private food sharing API for the Hungr application.
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateFoodDto,
  CredentialsDto,
  FoodEnvelopeDto,
  FoodListEnvelopeDto,
  GetHealth200,
  UpdateFoodDto,
  UpdateUserDto,
  UserEnvelopeDto
} from './model';

export const getHungrAPI = (axiosInstance: AxiosInstance = axios) => {
/**
 * @summary Register an account
 */
const register = (
    credentialsDto: CredentialsDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserEnvelopeDto>> => {
    return axiosInstance.post(
      `/api/v1/auth/register`,
      credentialsDto,options
    );
  }

/**
 * @summary Log in
 */
const login = (
    credentialsDto: CredentialsDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserEnvelopeDto>> => {
    return axiosInstance.post(
      `/api/v1/auth/login`,
      credentialsDto,options
    );
  }

/**
 * @summary Log out
 */
const logout = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/v1/auth/logout`,
      undefined,options
    );
  }

/**
 * @summary Get the authenticated session
 */
const getSession = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserEnvelopeDto>> => {
    return axiosInstance.get(
      `/api/v1/auth/session`,options
    );
  }

/**
 * @summary Get current user
 */
const getCurrentUser = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserEnvelopeDto>> => {
    return axiosInstance.get(
      `/api/v1/users/me`,options
    );
  }

/**
 * @summary Update current user
 */
const updateCurrentUser = (
    updateUserDto: UpdateUserDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserEnvelopeDto>> => {
    return axiosInstance.patch(
      `/api/v1/users/me`,
      updateUserDto,options
    );
  }

/**
 * @summary List your foods
 */
const listFoods = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<FoodListEnvelopeDto>> => {
    return axiosInstance.get(
      `/api/v1/foods`,options
    );
  }

/**
 * @summary Create a food
 */
const createFood = (
    createFoodDto: CreateFoodDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<FoodEnvelopeDto>> => {
    return axiosInstance.post(
      `/api/v1/foods`,
      createFoodDto,options
    );
  }

/**
 * @summary Get one of your foods
 */
const getFood = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<FoodEnvelopeDto>> => {
    return axiosInstance.get(
      `/api/v1/foods/${id}`,options
    );
  }

/**
 * @summary Update your food
 */
const updateFood = (
    id: string,
    updateFoodDto: UpdateFoodDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<FoodEnvelopeDto>> => {
    return axiosInstance.patch(
      `/api/v1/foods/${id}`,
      updateFoodDto,options
    );
  }

/**
 * @summary Delete your food
 */
const deleteFood = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(
      `/api/v1/foods/${id}`,options
    );
  }

/**
 * @summary Check API health
 */
const getHealth = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetHealth200>> => {
    return axiosInstance.get(
      `/healthz`,options
    );
  }

return {register,login,logout,getSession,getCurrentUser,updateCurrentUser,listFoods,createFood,getFood,updateFood,deleteFood,getHealth}};
export type RegisterResult = AxiosResponse<UserEnvelopeDto>
export type LoginResult = AxiosResponse<UserEnvelopeDto>
export type LogoutResult = AxiosResponse<void>
export type GetSessionResult = AxiosResponse<UserEnvelopeDto>
export type GetCurrentUserResult = AxiosResponse<UserEnvelopeDto>
export type UpdateCurrentUserResult = AxiosResponse<UserEnvelopeDto>
export type ListFoodsResult = AxiosResponse<FoodListEnvelopeDto>
export type CreateFoodResult = AxiosResponse<FoodEnvelopeDto>
export type GetFoodResult = AxiosResponse<FoodEnvelopeDto>
export type UpdateFoodResult = AxiosResponse<FoodEnvelopeDto>
export type DeleteFoodResult = AxiosResponse<void>
export type GetHealthResult = AxiosResponse<GetHealth200>
